name: Run Scrapper

on:
  workflow_dispatch:   # allow manual trigger
  schedule:
    - cron: "*/30 * * * *"   # runs every 30 minutes

jobs:
  run-scrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scrapper
        run: python scrapper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json [skip ci]" || echo "No changes to commit"
          git push
